In [2]:
using LinearAlgebra, Statistics

In [3]:
@show typeof(6.4)

typeof(6.4) = Float64


Float64

In [4]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [5]:
a = [1.0, 2.4, 3.0]

3-element Vector{Float64}:
 1.0
 2.4
 3.0

In [6]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [7]:
ndims(a)

1

In [8]:
[1 3 2]

1×3 Matrix{Int64}:
 1  3  2

In [9]:
fill(4.6, 3, 5)

3×5 Matrix{Float64}:
 4.6  4.6  4.6  4.6  4.6
 4.6  4.6  4.6  4.6  4.6
 4.6  4.6  4.6  4.6  4.6

In [10]:
x = [1, 2, 3]
y = x
y[1] = 2
x

3-element Vector{Int64}:
 2
 2
 3

In [11]:
x = [1, 2, 3]
y = copy(x)
y[1] = 2
x

3-element Vector{Int64}:
 1
 2
 3

In [12]:
# rather than making a copy of x, just crate a similarly sized array
x = [1, 2, 3]
y = similar(x)
y


3-element Vector{Int64}:
 0
 0
 0

In [13]:
x = [1, 2, 3]
y = similar(x, 2,2) # here it makes a 2x2 matrix
y

2×2 Matrix{Int64}:
 201267472  201267536
 201267504  201267568

In [14]:
a = [10 20 30 40]'

4×1 adjoint(::Matrix{Int64}) with eltype Int64:
 10
 20
 30
 40

In [15]:
[1;2;]

2-element Vector{Int64}:
 1
 2

In [16]:
[1;2;;]

2×1 Matrix{Int64}:
 1
 2

In [17]:
a = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [18]:
a[2:end] .= 2.3
@show a

a = [0.0, 2.3, 2.3, 2.3]


4-element Vector{Float64}:
 0.0
 2.3
 2.3
 2.3

# Vector and Slices

In [19]:
a = [1 2; 3 4]
b = a[:, 2]
@show b
a[:, 2] = [4,5] # moditify the second column of a
@show a
@show b;


b = [2, 4]
a = [1 4; 3 5]
b = [2, 4]


In [20]:
a = [1 2; 3 4]
@views b = a[:, 2]
@show b
a[:, 2] = [4,5] # moditify the second column of a
@show a
@show b;


b = [2, 4]
a = [1 4; 3 5]
b = [4, 5]


# Special Matrices

In [21]:
d = [1.0, 2.0]
a = Diagonal(d)

2×2 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅ 
  ⋅   2.0

# Assignment and Passing Arrays

In [22]:
x = [1 2 3]
y = x 

1×3 Matrix{Int64}:
 1  2  3

In [23]:
# consequence: one can rebind the name y
x = [1 2 3]
y = x     #  name `y` binds to whatever `x` bound to
z = [2 3 4]
y = z     # only change change name name binding, not value!
@show (x,y,z)

(x, y, z) = ([1 2 3], [2 3 4], [2 3 4])


([1 2 3], [2 3 4], [2 3 4])

In [24]:
# consequence: one can rebind the name y
x = [1 2 3]
y = x     #  name `y` binds to whatever `x` bound to
z = [2 3 4]
y .= z    #  Dispatching the assignment of each element
@show (x,y,z)

(x, y, z) = ([2 3 4], [2 3 4], [2 3 4])


([2 3 4], [2 3 4], [2 3 4])

### This applies to in-place functions as well

In [25]:
function f(x)
    return [1 2; 3 4]*x # matrix x column vector
end
val = [1, 2]
f(val)

2-element Vector{Int64}:
  5
 11

In [26]:
function f(x)
    return [1 2; 3 4]*x # matrix x column vector
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out .= [1 2; 3 4]*x
end
f!(y, val)
y

2-element Vector{Int64}:
  5
 11

In [29]:
function pro(parameters)
    (; a, b) = parameters
    return a*b
end
x = (; a=3.4,b= 4.5)
pro(x)

15.299999999999999

In [36]:
# In order to manage default values, use the @with_kw 

using Parameters

paramgen = @with_kw (α = 0.1, β = 0.2) # named tuples with default
@show paramgen(β = 3.5)

paramgen(β = 3.5) = (α = 0.1, β = 3.5)


(α = 0.1, β = 3.5)

### Noting, Missing, and Unions

In [37]:
typeof(nothing)

Nothing

In [38]:
function f(x)
    @assert x > 0.0
    sqrt(x)
end

@show f(1.0)
@show f(-2.5)

f(1.0) = 1.0


LoadError: AssertionError: x > 0.0

In [39]:
try sqrt(-1.2)
catch err
    err
end

DomainError(-1.2, "sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).")

In [10]:
size(a)

(3,)

In [3]:
x = (1, "test", 2.0)
@show typeof(x)

typeof(x) = Tuple{Int64, String, Float64}


Tuple{Int64, String, Float64}

In [4]:
# type hierachy
@show Float64 <: Real
@show Int64 <: Real
@show Complex{Float64} <: Real
@show Array <: Real;

Float64 <: Real = true
Int64 <: Real = true
Complex{Float64} <: Real = false
Array <: Real = false


In [5]:
using Base: show_supertypes  # import the function from the `Base` package

show_supertypes(Int64)

Int64 <: Signed <: Integer <: Real <: Number <: Any

In [1]:
using Base: @kwdef
using Parameters

@kwdef struct Foo5
    a::Float64 = 2.0     # adds default value
    b::Int64
    c::Vector{Float64}
end

foo = Foo5(a = 0.1, b = 2, c = [1.0, 2.0, 3.0])
foo2 = Foo5(c = [1.0, 2.0, 3.0], b = 2)  # rearrange order, uses default values

@show foo
@show foo2

function f(x)
    @unpack a, b, c = x     # can use `@unpack` on any struct
    return a + b + sum(c)
end

f(foo)

foo = Foo5(0.1, 2, [1.0, 2.0, 3.0])
foo2 = Foo5(2.0, 2, [1.0, 2.0, 3.0])


8.1